name = "finwise"
main = "src/index.ts"
compatibility_date = "2025-12-01"

[[kv_namespaces]]
binding = "USERS_KV"
id = "${USERS_KV_NAMESPACE_ID}"
preview_id = "${USERS_KV_PREVIEW_NAMESPACE_ID}"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "${SESSIONS_KV_NAMESPACE_ID}"
preview_id = "${SESSIONS_KV_PREVIEW_NAMESPACE_ID}"

[assets]
directory = "."
