name = "finwise"
main = "src/index.ts"
compatibility_date = "2025-12-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "USERS_KV"
id = "YOUR_USERS_KV_NAMESPACE_ID"
preview_id = "YOUR_USERS_KV_PREVIEW_NAMESPACE_ID"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "YOUR_SESSIONS_KV_NAMESPACE_ID"
preview_id = "YOUR_SESSIONS_KV_PREVIEW_NAMESPACE_ID"

[assets]
directory = "."
